language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: nVuiNP1qgkC791OQ5vGMN0A+THg06erYUfANoLfjERYuFKLGRYJ5rnBiEmCtfSnIRy+sURqZL1dbm4zarf2prRiKSqXK2B0wBgsaLkuAlNw0h9/pFZ+7NIMOnrHCtext0xbciXsMUQySgVRwxJx8UVJL2Y4JpFBe3KwZfqaRnX1jsFElX3ckDZ8tkPUtdTAuBNAbwi3BD5UwYCzPbIPmpcKEZGIy08YbdI0BJa7TkY5aVYYUgUhOrwH5MF1hBuy26rMVBQn29RnVJn5tD0Xo1XEHeAnL/BP+WKx4/S4G+qo1F9qFseBMacuU30b8u/qBprMkolgGijaDcp1Rc34gVW5V8eS+eBUOYnk8VKE9EVWgNaYbFlnKejHFxqmaNBczjYq/dJnxB4gNqCJXUdG0A8Ucwx063bnKNuw0W7oIf0egvt9al//cEeGXFc+OISOzt07F9WB5ZPKQcR5fxCcDTAdy9pzyvAV5KDBfWLM2wG+LKR21MnilLshB49Gz4B4UNhOEULXE1KeidgVOjjqsGcb2aZuWeX0dR7uZR9HEQRwcMqnzlgrWMISW852ZZ88l6RZ5GCjs+OXU9OntJw6QgduR+xTt5yC9/beSEv+XsC3OzmdsUxFVIWiB1YbScuILQz1et+5nRbRdqGQAnoIKNOxU4iI3DzLoVGvESXC0Fwo=
