<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<% String projectName = request.getContextPath(); %>
<!DOCTYPE html>
<html lang="en">
<head>
<title>Infinitiot (beta)</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="<%= projectName %>/resources/css/main.css">
<%-- favicons generated by http://realfavicongenerator.net/ --%>
<link rel="apple-touch-icon" sizes="57x57" href="<%= projectName %>/resources/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="<%= projectName %>/resources/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="<%= projectName %>/resources/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="<%= projectName %>/resources/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="<%= projectName %>/resources/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="<%= projectName %>/resources/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="<%= projectName %>/resources/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<%= projectName %>/resources/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="<%= projectName %>/resources/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="<%= projectName %>/resources/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="<%= projectName %>/resources/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="<%= projectName %>/resources/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="<%= projectName %>/resources/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="<%= projectName %>/resources/favicons/manifest.json">
<link rel="mask-icon" href="<%= projectName %>/resources/favicons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= projectName %>/resources/favicons/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://raw.githubusercontent.com/Caligatio/jsSHA/master/src/sha1.js"></script>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= projectName %>/">Smart P3</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if(session.getAttribute("user") == null) { %>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#login-email">Log in</a></li>
          <!-- <li><a href="#">Sign up</a></li> -->
        </ul>
        <% } else { %>
        <ul class="nav navbar-nav">
          <li><a href="<%= projectName %>/add-sensor">Nouveaux appareils</a></li>
          <li><a href="<%= projectName %>/node">Nœuds</a></li>
          <li><a href="<%= projectName %>/admin">Admin</a></li>
          <li><a href="<%= projectName %>/about-us">A propos</a></li>
          <%--
            <li><a href="<%= projectName %>/addSensor.jsp">Add Sensor/Node</a></li>
            <li><a href="<%= projectName %>/nodes.jsp">Nodes</a></li>
            <li><a href="<%= projectName %>/sensors.jsp">Sensors</a></li>
            <li><a href="<%= projectName %>/admin.jsp">Admin</a></li>
            <li><a href="<%= projectName %>/about-us.jsp">A propos</a></li>
            --%>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bienvenue<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <!-- <li><a href="<%= projectName %>/getting-started">Getting started</a></li> -->
              <li><a href="<%= projectName %>/auth/signout">Log out</a></li>
            </ul></li>
        </ul>
        <% } %>
      </div>
    </div>
  </nav>
  <div class="container">
    <!-- Alerts -->
    <% if(((String)session.getAttribute("errorMessage")) != null) { %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%=((String)session.getAttribute("errorMessage")) %>
    </div>
    <% } %>
